<?php

/**
 * @file
 * Contains hide_login_form.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function hide_login_form_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hide_login_form module.
    case 'help.page.hide_login_form':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Hide Login form.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hide_login_form_form_user_login_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  // Hide all form fields except for EU Login
  $form['name']['#access'] = FALSE;
  $form['pass']['#access'] = FALSE;
  $form['actions']['#access'] = FALSE;
  $form['captcha']['#access'] = FALSE;

  // Add field for EU image
  $form['eu_image'] = [
    '#markup' => '<div class="eu-login-image"></div>',
    '#weight' => -100,
  ];

  // Add css library to style EU Login button
  $form['#attached']['library'][] = 'hide_login_form/user_login_form';

}
